import React from 'react';
import { FileText, ArrowLeft } from 'lucide-react';

export default function CargoOSTermsPage() {
  return (
    <div className="min-h-screen font-sans">
      
      {/* Header */}
      <div className="bg-black text-white py-12 px-6">
        <div className="max-w-4xl mx-auto">
          <a href="/en/cargoos" className="inline-flex items-center gap-2 text-gray-400 hover:text-white text-sm mb-8 transition-colors">
            <ArrowLeft size={16} /> Back to CargoOS
          </a>
          <div className="flex items-center gap-3 mb-2">
            <FileText className="text-white" size={28} />
            <h1 className="text-3xl font-bold">Terms of Service</h1>
          </div>
          <p className="text-gray-400 text-sm">CargoOS by <span className="whitespace-nowrap">Gasp Maker LLC</span> — Last updated: July 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="bg-white max-w-4xl mx-auto px-6 py-12 space-y-10">

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">1. Agreement to Terms</h2>
          <p className="text-gray-600 leading-relaxed">
            By accessing or using CargoOS ("the Platform"), operated by <span className="whitespace-nowrap">Gasp Maker LLC</span> ("Company", "we", "us"), you ("Operator") agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">2. Description of Service</h2>
          <p className="text-gray-600 leading-relaxed">
            CargoOS is a white-label freight management Software-as-a-Service (SaaS) platform that allows logistics businesses ("Operators") to manage shipments, clients, virtual mailboxes, local deliveries, and billing under their own brand. CargoOS provides the technology infrastructure; Operators are responsible for their business operations and customer relationships.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">3. Subscription Plans & Payments</h2>
          <div className="space-y-3 text-gray-600 leading-relaxed">
            <p><strong className="text-gray-900">Setup Fee:</strong> A one-time setup fee of $500 USD is required to activate an Operator account. This fee is non-refundable.</p>
            <p><strong className="text-gray-900">Monthly Subscription:</strong> Operators are billed monthly in advance. Available plans are Starter ($149/mo), Growth ($299/mo), and Pro ($499/mo).</p>
            <p><strong className="text-gray-900">Payment Processing:</strong> All payments are processed via Stripe. By subscribing, you authorize recurring charges to your payment method.</p>
            <p><strong className="text-gray-900">Late Payment:</strong> Failure to pay within 7 days of the due date may result in service suspension. Accounts suspended for more than 30 days may be permanently terminated.</p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">4. Data Ownership</h2>
          <div className="space-y-3 text-gray-600 leading-relaxed">
            <p><strong className="text-gray-900">Operator Data:</strong> All data generated by the Operator's business — including client records, shipment history, and financial transactions — belongs exclusively to the Operator.</p>
            <p><strong className="text-gray-900">CargoOS Role:</strong> CargoOS acts solely as a Data Processor. We do not claim ownership of Operator or End User data, and we will never use it for marketing, resale, or any purpose beyond platform operation.</p>
            <p><strong className="text-gray-900">Data Export:</strong> Upon written request, CargoOS will provide a full data export within 30 business days.</p>
            <p><strong className="text-gray-900">Data Deletion:</strong> Upon cancellation, CargoOS will permanently delete all Operator data from its servers within 90 days of the subscription end date, after delivering the data export.</p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">5. Operator Responsibilities</h2>
          <ul className="list-disc list-inside space-y-2 text-gray-600 leading-relaxed">
            <li>Operators are responsible for complying with all applicable laws in their jurisdiction, including but not limited to USPS regulations for virtual mailbox services (39 CFR Part 111).</li>
            <li>Operators must obtain proper consent from their End Users before collecting and processing personal data.</li>
            <li>Operators are responsible for maintaining their own Stripe and EasyPost accounts and ensuring their API credentials remain secure.</li>
            <li>Operators may not use CargoOS to engage in illegal activities, fraud, or any activity that violates third-party terms of service.</li>
            <li>Operators are solely responsible for the accuracy of shipping information submitted through the platform.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">6. White-Label & Branding</h2>
          <p className="text-gray-600 leading-relaxed">
            CargoOS provides a white-label platform. Operators may customize the platform with their own logo, colors, and domain. CargoOS will not display its own branding to End Users of the Operator's platform. CargoOS reserves the right to reference Operators as customers for marketing purposes unless the Operator requests otherwise in writing.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">7. Intellectual Property</h2>
          <p className="text-gray-600 leading-relaxed">
            The CargoOS platform, including its software, design, and documentation, is the intellectual property of <span className="whitespace-nowrap">Gasp Maker LLC.</span> Operators are granted a limited, non-exclusive, non-transferable license to use the platform during their active subscription. This license does not grant ownership of any CargoOS technology.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">8. Service Availability & Support</h2>
          <div className="space-y-3 text-gray-600 leading-relaxed">
            <p>CargoOS targets 99% uptime but does not guarantee uninterrupted service. Scheduled maintenance will be communicated in advance when possible.</p>
            <p>Support is provided via email at <a href="mailto:hello@cargoos.io" className="text-black underline">hello@cargoos.io</a>. Response times vary by plan.</p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">9. Limitation of Liability</h2>
          <p className="text-gray-600 leading-relaxed">
            To the maximum extent permitted by law, <span className="whitespace-nowrap">Gasp Maker LLC</span> shall not be liable for any indirect, incidental, special, or consequential damages arising from the use of CargoOS, including but not limited to lost revenue, lost data, or business interruption. Our total liability to any Operator shall not exceed the amount paid by that Operator in the three months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">10. Termination</h2>
          <div className="space-y-3 text-gray-600 leading-relaxed">
            <p><strong className="text-gray-900">By Operator:</strong> Operators may cancel at any time by providing 30 days written notice to hello@cargoos.io. No refunds are issued for the current billing period.</p>
            <p><strong className="text-gray-900">By CargoOS:</strong> We reserve the right to terminate or suspend access for violation of these Terms, non-payment, or any activity that poses legal or security risks to the platform.</p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">11. Governing Law</h2>
          <p className="text-gray-600 leading-relaxed">
            These Terms are governed by the laws of the State of Florida, United States. Any disputes shall be resolved in the courts of Miami-Dade County, Florida.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">12. Changes to Terms</h2>
          <p className="text-gray-600 leading-relaxed">
            We may update these Terms at any time. Operators will be notified via email at least 30 days before material changes take effect. Continued use of the platform after the effective date constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">13. Contact</h2>
          <div className="p-5 bg-gray-50 rounded-xl border border-gray-200 text-sm text-gray-600">
            <p className="font-bold text-gray-900">Gasp Maker LLC — CargoOS</p>
            <p>1861 NW 22nd St, Miami, FL 33142</p>
            <p>Email: <a href="mailto:hello@cargoos.io" className="text-black underline">hello@cargoos.io</a></p>
            <p>Website: <a href="https://cargoos.io" className="text-black underline">cargoos.io</a></p>
          </div>
        </section>

      </div>

      {/* Footer */}
      <div className="bg-black py-8 text-center text-sm text-gray-500">
        © 2026 CargoOS by Gasp Maker LLC. All rights reserved.
      </div>

    </div>
  );
}